source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JKNotificationPanel-iPhone' do
  pod "JKNotificationPanel", :path => "../"
end

target 'JKNotificationPanel-iPad' do
  pod "JKNotificationPanel", :path => "../"
end

target 'JKNotificationPanel_Tests' do
  pod "JKNotificationPanel", :path => "../"
end
