source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JKNotificationPanel_Example', :exclusive => true do
  pod "JKNotificationPanel", :path => "../"
end

target 'JKNotificationPanel_Tests', :exclusive => true do
  pod "JKNotificationPanel", :path => "../"

  
end
