source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JKNotificationPanel-iPhone', :exclusive => true do
  pod "JKNotificationPanel", :path => "../"
end

target 'JKNotificationPanel-iPad', :exclusive => true do
  pod "JKNotificationPanel", :path => "../"
end

target 'JKNotificationPanel_Tests', :exclusive => true do
  pod "JKNotificationPanel", :path => "../"


end
